/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankPermissionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankPermissionResponse{}

// BankPermissionResponse Bank-level permission entry with scope identifiers.  Returned by GET /banks/:bank/permissions endpoints.
type BankPermissionResponse struct {
	BankId string `json:"bank_id"`
	ScopeType string `json:"scope_type"`
	ScopeId string `json:"scope_id"`
	Recall NullableBool `json:"recall,omitempty"`
	Retain NullableBool `json:"retain,omitempty"`
	RetainRoles []string `json:"retain_roles,omitempty"`
	RetainTags []string `json:"retain_tags,omitempty"`
	RetainEveryNTurns NullableInt32 `json:"retain_every_n_turns,omitempty"`
	RecallBudget NullableString `json:"recall_budget,omitempty"`
	RecallMaxTokens NullableInt32 `json:"recall_max_tokens,omitempty"`
	RecallTagGroups []map[string]interface{} `json:"recall_tag_groups,omitempty"`
	LlmModel NullableString `json:"llm_model,omitempty"`
	LlmProvider NullableString `json:"llm_provider,omitempty"`
	ExcludeProviders []string `json:"exclude_providers,omitempty"`
	RetainStrategy NullableString `json:"retain_strategy,omitempty"`
}

type _BankPermissionResponse BankPermissionResponse

// NewBankPermissionResponse instantiates a new BankPermissionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankPermissionResponse(bankId string, scopeType string, scopeId string) *BankPermissionResponse {
	this := BankPermissionResponse{}
	this.BankId = bankId
	this.ScopeType = scopeType
	this.ScopeId = scopeId
	return &this
}

// NewBankPermissionResponseWithDefaults instantiates a new BankPermissionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankPermissionResponseWithDefaults() *BankPermissionResponse {
	this := BankPermissionResponse{}
	return &this
}

// GetBankId returns the BankId field value
func (o *BankPermissionResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *BankPermissionResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *BankPermissionResponse) SetBankId(v string) {
	o.BankId = v
}

// GetScopeType returns the ScopeType field value
func (o *BankPermissionResponse) GetScopeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeType
}

// GetScopeTypeOk returns a tuple with the ScopeType field value
// and a boolean to check if the value has been set.
func (o *BankPermissionResponse) GetScopeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeType, true
}

// SetScopeType sets field value
func (o *BankPermissionResponse) SetScopeType(v string) {
	o.ScopeType = v
}

// GetScopeId returns the ScopeId field value
func (o *BankPermissionResponse) GetScopeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value
// and a boolean to check if the value has been set.
func (o *BankPermissionResponse) GetScopeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeId, true
}

// SetScopeId sets field value
func (o *BankPermissionResponse) SetScopeId(v string) {
	o.ScopeId = v
}

// GetRecall returns the Recall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRecall() bool {
	if o == nil || IsNil(o.Recall.Get()) {
		var ret bool
		return ret
	}
	return *o.Recall.Get()
}

// GetRecallOk returns a tuple with the Recall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRecallOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recall.Get(), o.Recall.IsSet()
}

// HasRecall returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRecall() bool {
	if o != nil && o.Recall.IsSet() {
		return true
	}

	return false
}

// SetRecall gets a reference to the given NullableBool and assigns it to the Recall field.
func (o *BankPermissionResponse) SetRecall(v bool) {
	o.Recall.Set(&v)
}
// SetRecallNil sets the value for Recall to be an explicit nil
func (o *BankPermissionResponse) SetRecallNil() {
	o.Recall.Set(nil)
}

// UnsetRecall ensures that no value is present for Recall, not even an explicit nil
func (o *BankPermissionResponse) UnsetRecall() {
	o.Recall.Unset()
}

// GetRetain returns the Retain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRetain() bool {
	if o == nil || IsNil(o.Retain.Get()) {
		var ret bool
		return ret
	}
	return *o.Retain.Get()
}

// GetRetainOk returns a tuple with the Retain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRetainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retain.Get(), o.Retain.IsSet()
}

// HasRetain returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRetain() bool {
	if o != nil && o.Retain.IsSet() {
		return true
	}

	return false
}

// SetRetain gets a reference to the given NullableBool and assigns it to the Retain field.
func (o *BankPermissionResponse) SetRetain(v bool) {
	o.Retain.Set(&v)
}
// SetRetainNil sets the value for Retain to be an explicit nil
func (o *BankPermissionResponse) SetRetainNil() {
	o.Retain.Set(nil)
}

// UnsetRetain ensures that no value is present for Retain, not even an explicit nil
func (o *BankPermissionResponse) UnsetRetain() {
	o.Retain.Unset()
}

// GetRetainRoles returns the RetainRoles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRetainRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RetainRoles
}

// GetRetainRolesOk returns a tuple with the RetainRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRetainRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.RetainRoles) {
		return nil, false
	}
	return o.RetainRoles, true
}

// HasRetainRoles returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRetainRoles() bool {
	if o != nil && !IsNil(o.RetainRoles) {
		return true
	}

	return false
}

// SetRetainRoles gets a reference to the given []string and assigns it to the RetainRoles field.
func (o *BankPermissionResponse) SetRetainRoles(v []string) {
	o.RetainRoles = v
}

// GetRetainTags returns the RetainTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRetainTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RetainTags
}

// GetRetainTagsOk returns a tuple with the RetainTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRetainTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.RetainTags) {
		return nil, false
	}
	return o.RetainTags, true
}

// HasRetainTags returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRetainTags() bool {
	if o != nil && !IsNil(o.RetainTags) {
		return true
	}

	return false
}

// SetRetainTags gets a reference to the given []string and assigns it to the RetainTags field.
func (o *BankPermissionResponse) SetRetainTags(v []string) {
	o.RetainTags = v
}

// GetRetainEveryNTurns returns the RetainEveryNTurns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRetainEveryNTurns() int32 {
	if o == nil || IsNil(o.RetainEveryNTurns.Get()) {
		var ret int32
		return ret
	}
	return *o.RetainEveryNTurns.Get()
}

// GetRetainEveryNTurnsOk returns a tuple with the RetainEveryNTurns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRetainEveryNTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainEveryNTurns.Get(), o.RetainEveryNTurns.IsSet()
}

// HasRetainEveryNTurns returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRetainEveryNTurns() bool {
	if o != nil && o.RetainEveryNTurns.IsSet() {
		return true
	}

	return false
}

// SetRetainEveryNTurns gets a reference to the given NullableInt32 and assigns it to the RetainEveryNTurns field.
func (o *BankPermissionResponse) SetRetainEveryNTurns(v int32) {
	o.RetainEveryNTurns.Set(&v)
}
// SetRetainEveryNTurnsNil sets the value for RetainEveryNTurns to be an explicit nil
func (o *BankPermissionResponse) SetRetainEveryNTurnsNil() {
	o.RetainEveryNTurns.Set(nil)
}

// UnsetRetainEveryNTurns ensures that no value is present for RetainEveryNTurns, not even an explicit nil
func (o *BankPermissionResponse) UnsetRetainEveryNTurns() {
	o.RetainEveryNTurns.Unset()
}

// GetRecallBudget returns the RecallBudget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRecallBudget() string {
	if o == nil || IsNil(o.RecallBudget.Get()) {
		var ret string
		return ret
	}
	return *o.RecallBudget.Get()
}

// GetRecallBudgetOk returns a tuple with the RecallBudget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRecallBudgetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallBudget.Get(), o.RecallBudget.IsSet()
}

// HasRecallBudget returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRecallBudget() bool {
	if o != nil && o.RecallBudget.IsSet() {
		return true
	}

	return false
}

// SetRecallBudget gets a reference to the given NullableString and assigns it to the RecallBudget field.
func (o *BankPermissionResponse) SetRecallBudget(v string) {
	o.RecallBudget.Set(&v)
}
// SetRecallBudgetNil sets the value for RecallBudget to be an explicit nil
func (o *BankPermissionResponse) SetRecallBudgetNil() {
	o.RecallBudget.Set(nil)
}

// UnsetRecallBudget ensures that no value is present for RecallBudget, not even an explicit nil
func (o *BankPermissionResponse) UnsetRecallBudget() {
	o.RecallBudget.Unset()
}

// GetRecallMaxTokens returns the RecallMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRecallMaxTokens() int32 {
	if o == nil || IsNil(o.RecallMaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.RecallMaxTokens.Get()
}

// GetRecallMaxTokensOk returns a tuple with the RecallMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRecallMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallMaxTokens.Get(), o.RecallMaxTokens.IsSet()
}

// HasRecallMaxTokens returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRecallMaxTokens() bool {
	if o != nil && o.RecallMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetRecallMaxTokens gets a reference to the given NullableInt32 and assigns it to the RecallMaxTokens field.
func (o *BankPermissionResponse) SetRecallMaxTokens(v int32) {
	o.RecallMaxTokens.Set(&v)
}
// SetRecallMaxTokensNil sets the value for RecallMaxTokens to be an explicit nil
func (o *BankPermissionResponse) SetRecallMaxTokensNil() {
	o.RecallMaxTokens.Set(nil)
}

// UnsetRecallMaxTokens ensures that no value is present for RecallMaxTokens, not even an explicit nil
func (o *BankPermissionResponse) UnsetRecallMaxTokens() {
	o.RecallMaxTokens.Unset()
}

// GetRecallTagGroups returns the RecallTagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRecallTagGroups() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.RecallTagGroups
}

// GetRecallTagGroupsOk returns a tuple with the RecallTagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRecallTagGroupsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.RecallTagGroups) {
		return nil, false
	}
	return o.RecallTagGroups, true
}

// HasRecallTagGroups returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRecallTagGroups() bool {
	if o != nil && !IsNil(o.RecallTagGroups) {
		return true
	}

	return false
}

// SetRecallTagGroups gets a reference to the given []map[string]interface{} and assigns it to the RecallTagGroups field.
func (o *BankPermissionResponse) SetRecallTagGroups(v []map[string]interface{}) {
	o.RecallTagGroups = v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel.Get()) {
		var ret string
		return ret
	}
	return *o.LlmModel.Get()
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetLlmModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmModel.Get(), o.LlmModel.IsSet()
}

// HasLlmModel returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasLlmModel() bool {
	if o != nil && o.LlmModel.IsSet() {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given NullableString and assigns it to the LlmModel field.
func (o *BankPermissionResponse) SetLlmModel(v string) {
	o.LlmModel.Set(&v)
}
// SetLlmModelNil sets the value for LlmModel to be an explicit nil
func (o *BankPermissionResponse) SetLlmModelNil() {
	o.LlmModel.Set(nil)
}

// UnsetLlmModel ensures that no value is present for LlmModel, not even an explicit nil
func (o *BankPermissionResponse) UnsetLlmModel() {
	o.LlmModel.Unset()
}

// GetLlmProvider returns the LlmProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetLlmProvider() string {
	if o == nil || IsNil(o.LlmProvider.Get()) {
		var ret string
		return ret
	}
	return *o.LlmProvider.Get()
}

// GetLlmProviderOk returns a tuple with the LlmProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetLlmProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmProvider.Get(), o.LlmProvider.IsSet()
}

// HasLlmProvider returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasLlmProvider() bool {
	if o != nil && o.LlmProvider.IsSet() {
		return true
	}

	return false
}

// SetLlmProvider gets a reference to the given NullableString and assigns it to the LlmProvider field.
func (o *BankPermissionResponse) SetLlmProvider(v string) {
	o.LlmProvider.Set(&v)
}
// SetLlmProviderNil sets the value for LlmProvider to be an explicit nil
func (o *BankPermissionResponse) SetLlmProviderNil() {
	o.LlmProvider.Set(nil)
}

// UnsetLlmProvider ensures that no value is present for LlmProvider, not even an explicit nil
func (o *BankPermissionResponse) UnsetLlmProvider() {
	o.LlmProvider.Unset()
}

// GetExcludeProviders returns the ExcludeProviders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetExcludeProviders() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeProviders
}

// GetExcludeProvidersOk returns a tuple with the ExcludeProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetExcludeProvidersOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeProviders) {
		return nil, false
	}
	return o.ExcludeProviders, true
}

// HasExcludeProviders returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasExcludeProviders() bool {
	if o != nil && !IsNil(o.ExcludeProviders) {
		return true
	}

	return false
}

// SetExcludeProviders gets a reference to the given []string and assigns it to the ExcludeProviders field.
func (o *BankPermissionResponse) SetExcludeProviders(v []string) {
	o.ExcludeProviders = v
}

// GetRetainStrategy returns the RetainStrategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankPermissionResponse) GetRetainStrategy() string {
	if o == nil || IsNil(o.RetainStrategy.Get()) {
		var ret string
		return ret
	}
	return *o.RetainStrategy.Get()
}

// GetRetainStrategyOk returns a tuple with the RetainStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankPermissionResponse) GetRetainStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainStrategy.Get(), o.RetainStrategy.IsSet()
}

// HasRetainStrategy returns a boolean if a field has been set.
func (o *BankPermissionResponse) HasRetainStrategy() bool {
	if o != nil && o.RetainStrategy.IsSet() {
		return true
	}

	return false
}

// SetRetainStrategy gets a reference to the given NullableString and assigns it to the RetainStrategy field.
func (o *BankPermissionResponse) SetRetainStrategy(v string) {
	o.RetainStrategy.Set(&v)
}
// SetRetainStrategyNil sets the value for RetainStrategy to be an explicit nil
func (o *BankPermissionResponse) SetRetainStrategyNil() {
	o.RetainStrategy.Set(nil)
}

// UnsetRetainStrategy ensures that no value is present for RetainStrategy, not even an explicit nil
func (o *BankPermissionResponse) UnsetRetainStrategy() {
	o.RetainStrategy.Unset()
}

func (o BankPermissionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankPermissionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["scope_type"] = o.ScopeType
	toSerialize["scope_id"] = o.ScopeId
	if o.Recall.IsSet() {
		toSerialize["recall"] = o.Recall.Get()
	}
	if o.Retain.IsSet() {
		toSerialize["retain"] = o.Retain.Get()
	}
	if o.RetainRoles != nil {
		toSerialize["retain_roles"] = o.RetainRoles
	}
	if o.RetainTags != nil {
		toSerialize["retain_tags"] = o.RetainTags
	}
	if o.RetainEveryNTurns.IsSet() {
		toSerialize["retain_every_n_turns"] = o.RetainEveryNTurns.Get()
	}
	if o.RecallBudget.IsSet() {
		toSerialize["recall_budget"] = o.RecallBudget.Get()
	}
	if o.RecallMaxTokens.IsSet() {
		toSerialize["recall_max_tokens"] = o.RecallMaxTokens.Get()
	}
	if o.RecallTagGroups != nil {
		toSerialize["recall_tag_groups"] = o.RecallTagGroups
	}
	if o.LlmModel.IsSet() {
		toSerialize["llm_model"] = o.LlmModel.Get()
	}
	if o.LlmProvider.IsSet() {
		toSerialize["llm_provider"] = o.LlmProvider.Get()
	}
	if o.ExcludeProviders != nil {
		toSerialize["exclude_providers"] = o.ExcludeProviders
	}
	if o.RetainStrategy.IsSet() {
		toSerialize["retain_strategy"] = o.RetainStrategy.Get()
	}
	return toSerialize, nil
}

func (o *BankPermissionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"scope_type",
		"scope_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankPermissionResponse := _BankPermissionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankPermissionResponse)

	if err != nil {
		return err
	}

	*o = BankPermissionResponse(varBankPermissionResponse)

	return err
}

type NullableBankPermissionResponse struct {
	value *BankPermissionResponse
	isSet bool
}

func (v NullableBankPermissionResponse) Get() *BankPermissionResponse {
	return v.value
}

func (v *NullableBankPermissionResponse) Set(val *BankPermissionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBankPermissionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBankPermissionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankPermissionResponse(val *BankPermissionResponse) *NullableBankPermissionResponse {
	return &NullableBankPermissionResponse{value: val, isSet: true}
}

func (v NullableBankPermissionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankPermissionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


