/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
)

// checks if the UpdateGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupRequest{}

// UpdateGroupRequest struct for UpdateGroupRequest
type UpdateGroupRequest struct {
	DisplayName NullableString `json:"display_name,omitempty"`
	Recall NullableBool `json:"recall,omitempty"`
	Retain NullableBool `json:"retain,omitempty"`
	RetainRoles []string `json:"retain_roles,omitempty"`
	RetainTags []string `json:"retain_tags,omitempty"`
	RetainEveryNTurns NullableInt32 `json:"retain_every_n_turns,omitempty"`
	RecallBudget NullableString `json:"recall_budget,omitempty"`
	RecallMaxTokens NullableInt32 `json:"recall_max_tokens,omitempty"`
	RecallTagGroups []map[string]interface{} `json:"recall_tag_groups,omitempty"`
	LlmModel NullableString `json:"llm_model,omitempty"`
	LlmProvider NullableString `json:"llm_provider,omitempty"`
	ExcludeProviders []string `json:"exclude_providers,omitempty"`
	RetainStrategy NullableString `json:"retain_strategy,omitempty"`
}

// NewUpdateGroupRequest instantiates a new UpdateGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupRequest() *UpdateGroupRequest {
	this := UpdateGroupRequest{}
	return &this
}

// NewUpdateGroupRequestWithDefaults instantiates a new UpdateGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupRequestWithDefaults() *UpdateGroupRequest {
	this := UpdateGroupRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *UpdateGroupRequest) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *UpdateGroupRequest) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *UpdateGroupRequest) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetRecall returns the Recall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRecall() bool {
	if o == nil || IsNil(o.Recall.Get()) {
		var ret bool
		return ret
	}
	return *o.Recall.Get()
}

// GetRecallOk returns a tuple with the Recall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRecallOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recall.Get(), o.Recall.IsSet()
}

// HasRecall returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRecall() bool {
	if o != nil && o.Recall.IsSet() {
		return true
	}

	return false
}

// SetRecall gets a reference to the given NullableBool and assigns it to the Recall field.
func (o *UpdateGroupRequest) SetRecall(v bool) {
	o.Recall.Set(&v)
}
// SetRecallNil sets the value for Recall to be an explicit nil
func (o *UpdateGroupRequest) SetRecallNil() {
	o.Recall.Set(nil)
}

// UnsetRecall ensures that no value is present for Recall, not even an explicit nil
func (o *UpdateGroupRequest) UnsetRecall() {
	o.Recall.Unset()
}

// GetRetain returns the Retain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRetain() bool {
	if o == nil || IsNil(o.Retain.Get()) {
		var ret bool
		return ret
	}
	return *o.Retain.Get()
}

// GetRetainOk returns a tuple with the Retain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRetainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retain.Get(), o.Retain.IsSet()
}

// HasRetain returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRetain() bool {
	if o != nil && o.Retain.IsSet() {
		return true
	}

	return false
}

// SetRetain gets a reference to the given NullableBool and assigns it to the Retain field.
func (o *UpdateGroupRequest) SetRetain(v bool) {
	o.Retain.Set(&v)
}
// SetRetainNil sets the value for Retain to be an explicit nil
func (o *UpdateGroupRequest) SetRetainNil() {
	o.Retain.Set(nil)
}

// UnsetRetain ensures that no value is present for Retain, not even an explicit nil
func (o *UpdateGroupRequest) UnsetRetain() {
	o.Retain.Unset()
}

// GetRetainRoles returns the RetainRoles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRetainRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RetainRoles
}

// GetRetainRolesOk returns a tuple with the RetainRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRetainRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.RetainRoles) {
		return nil, false
	}
	return o.RetainRoles, true
}

// HasRetainRoles returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRetainRoles() bool {
	if o != nil && !IsNil(o.RetainRoles) {
		return true
	}

	return false
}

// SetRetainRoles gets a reference to the given []string and assigns it to the RetainRoles field.
func (o *UpdateGroupRequest) SetRetainRoles(v []string) {
	o.RetainRoles = v
}

// GetRetainTags returns the RetainTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRetainTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RetainTags
}

// GetRetainTagsOk returns a tuple with the RetainTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRetainTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.RetainTags) {
		return nil, false
	}
	return o.RetainTags, true
}

// HasRetainTags returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRetainTags() bool {
	if o != nil && !IsNil(o.RetainTags) {
		return true
	}

	return false
}

// SetRetainTags gets a reference to the given []string and assigns it to the RetainTags field.
func (o *UpdateGroupRequest) SetRetainTags(v []string) {
	o.RetainTags = v
}

// GetRetainEveryNTurns returns the RetainEveryNTurns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRetainEveryNTurns() int32 {
	if o == nil || IsNil(o.RetainEveryNTurns.Get()) {
		var ret int32
		return ret
	}
	return *o.RetainEveryNTurns.Get()
}

// GetRetainEveryNTurnsOk returns a tuple with the RetainEveryNTurns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRetainEveryNTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainEveryNTurns.Get(), o.RetainEveryNTurns.IsSet()
}

// HasRetainEveryNTurns returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRetainEveryNTurns() bool {
	if o != nil && o.RetainEveryNTurns.IsSet() {
		return true
	}

	return false
}

// SetRetainEveryNTurns gets a reference to the given NullableInt32 and assigns it to the RetainEveryNTurns field.
func (o *UpdateGroupRequest) SetRetainEveryNTurns(v int32) {
	o.RetainEveryNTurns.Set(&v)
}
// SetRetainEveryNTurnsNil sets the value for RetainEveryNTurns to be an explicit nil
func (o *UpdateGroupRequest) SetRetainEveryNTurnsNil() {
	o.RetainEveryNTurns.Set(nil)
}

// UnsetRetainEveryNTurns ensures that no value is present for RetainEveryNTurns, not even an explicit nil
func (o *UpdateGroupRequest) UnsetRetainEveryNTurns() {
	o.RetainEveryNTurns.Unset()
}

// GetRecallBudget returns the RecallBudget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRecallBudget() string {
	if o == nil || IsNil(o.RecallBudget.Get()) {
		var ret string
		return ret
	}
	return *o.RecallBudget.Get()
}

// GetRecallBudgetOk returns a tuple with the RecallBudget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRecallBudgetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallBudget.Get(), o.RecallBudget.IsSet()
}

// HasRecallBudget returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRecallBudget() bool {
	if o != nil && o.RecallBudget.IsSet() {
		return true
	}

	return false
}

// SetRecallBudget gets a reference to the given NullableString and assigns it to the RecallBudget field.
func (o *UpdateGroupRequest) SetRecallBudget(v string) {
	o.RecallBudget.Set(&v)
}
// SetRecallBudgetNil sets the value for RecallBudget to be an explicit nil
func (o *UpdateGroupRequest) SetRecallBudgetNil() {
	o.RecallBudget.Set(nil)
}

// UnsetRecallBudget ensures that no value is present for RecallBudget, not even an explicit nil
func (o *UpdateGroupRequest) UnsetRecallBudget() {
	o.RecallBudget.Unset()
}

// GetRecallMaxTokens returns the RecallMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRecallMaxTokens() int32 {
	if o == nil || IsNil(o.RecallMaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.RecallMaxTokens.Get()
}

// GetRecallMaxTokensOk returns a tuple with the RecallMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRecallMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallMaxTokens.Get(), o.RecallMaxTokens.IsSet()
}

// HasRecallMaxTokens returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRecallMaxTokens() bool {
	if o != nil && o.RecallMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetRecallMaxTokens gets a reference to the given NullableInt32 and assigns it to the RecallMaxTokens field.
func (o *UpdateGroupRequest) SetRecallMaxTokens(v int32) {
	o.RecallMaxTokens.Set(&v)
}
// SetRecallMaxTokensNil sets the value for RecallMaxTokens to be an explicit nil
func (o *UpdateGroupRequest) SetRecallMaxTokensNil() {
	o.RecallMaxTokens.Set(nil)
}

// UnsetRecallMaxTokens ensures that no value is present for RecallMaxTokens, not even an explicit nil
func (o *UpdateGroupRequest) UnsetRecallMaxTokens() {
	o.RecallMaxTokens.Unset()
}

// GetRecallTagGroups returns the RecallTagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRecallTagGroups() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.RecallTagGroups
}

// GetRecallTagGroupsOk returns a tuple with the RecallTagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRecallTagGroupsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.RecallTagGroups) {
		return nil, false
	}
	return o.RecallTagGroups, true
}

// HasRecallTagGroups returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRecallTagGroups() bool {
	if o != nil && !IsNil(o.RecallTagGroups) {
		return true
	}

	return false
}

// SetRecallTagGroups gets a reference to the given []map[string]interface{} and assigns it to the RecallTagGroups field.
func (o *UpdateGroupRequest) SetRecallTagGroups(v []map[string]interface{}) {
	o.RecallTagGroups = v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel.Get()) {
		var ret string
		return ret
	}
	return *o.LlmModel.Get()
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetLlmModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmModel.Get(), o.LlmModel.IsSet()
}

// HasLlmModel returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasLlmModel() bool {
	if o != nil && o.LlmModel.IsSet() {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given NullableString and assigns it to the LlmModel field.
func (o *UpdateGroupRequest) SetLlmModel(v string) {
	o.LlmModel.Set(&v)
}
// SetLlmModelNil sets the value for LlmModel to be an explicit nil
func (o *UpdateGroupRequest) SetLlmModelNil() {
	o.LlmModel.Set(nil)
}

// UnsetLlmModel ensures that no value is present for LlmModel, not even an explicit nil
func (o *UpdateGroupRequest) UnsetLlmModel() {
	o.LlmModel.Unset()
}

// GetLlmProvider returns the LlmProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetLlmProvider() string {
	if o == nil || IsNil(o.LlmProvider.Get()) {
		var ret string
		return ret
	}
	return *o.LlmProvider.Get()
}

// GetLlmProviderOk returns a tuple with the LlmProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetLlmProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmProvider.Get(), o.LlmProvider.IsSet()
}

// HasLlmProvider returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasLlmProvider() bool {
	if o != nil && o.LlmProvider.IsSet() {
		return true
	}

	return false
}

// SetLlmProvider gets a reference to the given NullableString and assigns it to the LlmProvider field.
func (o *UpdateGroupRequest) SetLlmProvider(v string) {
	o.LlmProvider.Set(&v)
}
// SetLlmProviderNil sets the value for LlmProvider to be an explicit nil
func (o *UpdateGroupRequest) SetLlmProviderNil() {
	o.LlmProvider.Set(nil)
}

// UnsetLlmProvider ensures that no value is present for LlmProvider, not even an explicit nil
func (o *UpdateGroupRequest) UnsetLlmProvider() {
	o.LlmProvider.Unset()
}

// GetExcludeProviders returns the ExcludeProviders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetExcludeProviders() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeProviders
}

// GetExcludeProvidersOk returns a tuple with the ExcludeProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetExcludeProvidersOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeProviders) {
		return nil, false
	}
	return o.ExcludeProviders, true
}

// HasExcludeProviders returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasExcludeProviders() bool {
	if o != nil && !IsNil(o.ExcludeProviders) {
		return true
	}

	return false
}

// SetExcludeProviders gets a reference to the given []string and assigns it to the ExcludeProviders field.
func (o *UpdateGroupRequest) SetExcludeProviders(v []string) {
	o.ExcludeProviders = v
}

// GetRetainStrategy returns the RetainStrategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateGroupRequest) GetRetainStrategy() string {
	if o == nil || IsNil(o.RetainStrategy.Get()) {
		var ret string
		return ret
	}
	return *o.RetainStrategy.Get()
}

// GetRetainStrategyOk returns a tuple with the RetainStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateGroupRequest) GetRetainStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainStrategy.Get(), o.RetainStrategy.IsSet()
}

// HasRetainStrategy returns a boolean if a field has been set.
func (o *UpdateGroupRequest) HasRetainStrategy() bool {
	if o != nil && o.RetainStrategy.IsSet() {
		return true
	}

	return false
}

// SetRetainStrategy gets a reference to the given NullableString and assigns it to the RetainStrategy field.
func (o *UpdateGroupRequest) SetRetainStrategy(v string) {
	o.RetainStrategy.Set(&v)
}
// SetRetainStrategyNil sets the value for RetainStrategy to be an explicit nil
func (o *UpdateGroupRequest) SetRetainStrategyNil() {
	o.RetainStrategy.Set(nil)
}

// UnsetRetainStrategy ensures that no value is present for RetainStrategy, not even an explicit nil
func (o *UpdateGroupRequest) UnsetRetainStrategy() {
	o.RetainStrategy.Unset()
}

func (o UpdateGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DisplayName.IsSet() {
		toSerialize["display_name"] = o.DisplayName.Get()
	}
	if o.Recall.IsSet() {
		toSerialize["recall"] = o.Recall.Get()
	}
	if o.Retain.IsSet() {
		toSerialize["retain"] = o.Retain.Get()
	}
	if o.RetainRoles != nil {
		toSerialize["retain_roles"] = o.RetainRoles
	}
	if o.RetainTags != nil {
		toSerialize["retain_tags"] = o.RetainTags
	}
	if o.RetainEveryNTurns.IsSet() {
		toSerialize["retain_every_n_turns"] = o.RetainEveryNTurns.Get()
	}
	if o.RecallBudget.IsSet() {
		toSerialize["recall_budget"] = o.RecallBudget.Get()
	}
	if o.RecallMaxTokens.IsSet() {
		toSerialize["recall_max_tokens"] = o.RecallMaxTokens.Get()
	}
	if o.RecallTagGroups != nil {
		toSerialize["recall_tag_groups"] = o.RecallTagGroups
	}
	if o.LlmModel.IsSet() {
		toSerialize["llm_model"] = o.LlmModel.Get()
	}
	if o.LlmProvider.IsSet() {
		toSerialize["llm_provider"] = o.LlmProvider.Get()
	}
	if o.ExcludeProviders != nil {
		toSerialize["exclude_providers"] = o.ExcludeProviders
	}
	if o.RetainStrategy.IsSet() {
		toSerialize["retain_strategy"] = o.RetainStrategy.Get()
	}
	return toSerialize, nil
}

type NullableUpdateGroupRequest struct {
	value *UpdateGroupRequest
	isSet bool
}

func (v NullableUpdateGroupRequest) Get() *UpdateGroupRequest {
	return v.value
}

func (v *NullableUpdateGroupRequest) Set(val *UpdateGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupRequest(val *UpdateGroupRequest) *NullableUpdateGroupRequest {
	return &NullableUpdateGroupRequest{value: val, isSet: true}
}

func (v NullableUpdateGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


