/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupResponse{}

// GroupResponse Group resource with all permission fields.  Returned by GET /groups/:id and POST /groups. Permission fields are nullable — None means \"not set (inherit from global).\"
type GroupResponse struct {
	Id string `json:"id"`
	DisplayName string `json:"display_name"`
	Recall NullableBool `json:"recall,omitempty"`
	Retain NullableBool `json:"retain,omitempty"`
	RetainRoles []string `json:"retain_roles,omitempty"`
	RetainTags []string `json:"retain_tags,omitempty"`
	RetainEveryNTurns NullableInt32 `json:"retain_every_n_turns,omitempty"`
	RecallBudget NullableString `json:"recall_budget,omitempty"`
	RecallMaxTokens NullableInt32 `json:"recall_max_tokens,omitempty"`
	RecallTagGroups []map[string]interface{} `json:"recall_tag_groups,omitempty"`
	LlmModel NullableString `json:"llm_model,omitempty"`
	LlmProvider NullableString `json:"llm_provider,omitempty"`
	ExcludeProviders []string `json:"exclude_providers,omitempty"`
	RetainStrategy NullableString `json:"retain_strategy,omitempty"`
}

type _GroupResponse GroupResponse

// NewGroupResponse instantiates a new GroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupResponse(id string, displayName string) *GroupResponse {
	this := GroupResponse{}
	this.Id = id
	this.DisplayName = displayName
	return &this
}

// NewGroupResponseWithDefaults instantiates a new GroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupResponseWithDefaults() *GroupResponse {
	this := GroupResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GroupResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupResponse) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *GroupResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *GroupResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *GroupResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetRecall returns the Recall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRecall() bool {
	if o == nil || IsNil(o.Recall.Get()) {
		var ret bool
		return ret
	}
	return *o.Recall.Get()
}

// GetRecallOk returns a tuple with the Recall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRecallOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recall.Get(), o.Recall.IsSet()
}

// HasRecall returns a boolean if a field has been set.
func (o *GroupResponse) HasRecall() bool {
	if o != nil && o.Recall.IsSet() {
		return true
	}

	return false
}

// SetRecall gets a reference to the given NullableBool and assigns it to the Recall field.
func (o *GroupResponse) SetRecall(v bool) {
	o.Recall.Set(&v)
}
// SetRecallNil sets the value for Recall to be an explicit nil
func (o *GroupResponse) SetRecallNil() {
	o.Recall.Set(nil)
}

// UnsetRecall ensures that no value is present for Recall, not even an explicit nil
func (o *GroupResponse) UnsetRecall() {
	o.Recall.Unset()
}

// GetRetain returns the Retain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRetain() bool {
	if o == nil || IsNil(o.Retain.Get()) {
		var ret bool
		return ret
	}
	return *o.Retain.Get()
}

// GetRetainOk returns a tuple with the Retain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRetainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retain.Get(), o.Retain.IsSet()
}

// HasRetain returns a boolean if a field has been set.
func (o *GroupResponse) HasRetain() bool {
	if o != nil && o.Retain.IsSet() {
		return true
	}

	return false
}

// SetRetain gets a reference to the given NullableBool and assigns it to the Retain field.
func (o *GroupResponse) SetRetain(v bool) {
	o.Retain.Set(&v)
}
// SetRetainNil sets the value for Retain to be an explicit nil
func (o *GroupResponse) SetRetainNil() {
	o.Retain.Set(nil)
}

// UnsetRetain ensures that no value is present for Retain, not even an explicit nil
func (o *GroupResponse) UnsetRetain() {
	o.Retain.Unset()
}

// GetRetainRoles returns the RetainRoles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRetainRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RetainRoles
}

// GetRetainRolesOk returns a tuple with the RetainRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRetainRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.RetainRoles) {
		return nil, false
	}
	return o.RetainRoles, true
}

// HasRetainRoles returns a boolean if a field has been set.
func (o *GroupResponse) HasRetainRoles() bool {
	if o != nil && !IsNil(o.RetainRoles) {
		return true
	}

	return false
}

// SetRetainRoles gets a reference to the given []string and assigns it to the RetainRoles field.
func (o *GroupResponse) SetRetainRoles(v []string) {
	o.RetainRoles = v
}

// GetRetainTags returns the RetainTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRetainTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RetainTags
}

// GetRetainTagsOk returns a tuple with the RetainTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRetainTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.RetainTags) {
		return nil, false
	}
	return o.RetainTags, true
}

// HasRetainTags returns a boolean if a field has been set.
func (o *GroupResponse) HasRetainTags() bool {
	if o != nil && !IsNil(o.RetainTags) {
		return true
	}

	return false
}

// SetRetainTags gets a reference to the given []string and assigns it to the RetainTags field.
func (o *GroupResponse) SetRetainTags(v []string) {
	o.RetainTags = v
}

// GetRetainEveryNTurns returns the RetainEveryNTurns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRetainEveryNTurns() int32 {
	if o == nil || IsNil(o.RetainEveryNTurns.Get()) {
		var ret int32
		return ret
	}
	return *o.RetainEveryNTurns.Get()
}

// GetRetainEveryNTurnsOk returns a tuple with the RetainEveryNTurns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRetainEveryNTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainEveryNTurns.Get(), o.RetainEveryNTurns.IsSet()
}

// HasRetainEveryNTurns returns a boolean if a field has been set.
func (o *GroupResponse) HasRetainEveryNTurns() bool {
	if o != nil && o.RetainEveryNTurns.IsSet() {
		return true
	}

	return false
}

// SetRetainEveryNTurns gets a reference to the given NullableInt32 and assigns it to the RetainEveryNTurns field.
func (o *GroupResponse) SetRetainEveryNTurns(v int32) {
	o.RetainEveryNTurns.Set(&v)
}
// SetRetainEveryNTurnsNil sets the value for RetainEveryNTurns to be an explicit nil
func (o *GroupResponse) SetRetainEveryNTurnsNil() {
	o.RetainEveryNTurns.Set(nil)
}

// UnsetRetainEveryNTurns ensures that no value is present for RetainEveryNTurns, not even an explicit nil
func (o *GroupResponse) UnsetRetainEveryNTurns() {
	o.RetainEveryNTurns.Unset()
}

// GetRecallBudget returns the RecallBudget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRecallBudget() string {
	if o == nil || IsNil(o.RecallBudget.Get()) {
		var ret string
		return ret
	}
	return *o.RecallBudget.Get()
}

// GetRecallBudgetOk returns a tuple with the RecallBudget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRecallBudgetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallBudget.Get(), o.RecallBudget.IsSet()
}

// HasRecallBudget returns a boolean if a field has been set.
func (o *GroupResponse) HasRecallBudget() bool {
	if o != nil && o.RecallBudget.IsSet() {
		return true
	}

	return false
}

// SetRecallBudget gets a reference to the given NullableString and assigns it to the RecallBudget field.
func (o *GroupResponse) SetRecallBudget(v string) {
	o.RecallBudget.Set(&v)
}
// SetRecallBudgetNil sets the value for RecallBudget to be an explicit nil
func (o *GroupResponse) SetRecallBudgetNil() {
	o.RecallBudget.Set(nil)
}

// UnsetRecallBudget ensures that no value is present for RecallBudget, not even an explicit nil
func (o *GroupResponse) UnsetRecallBudget() {
	o.RecallBudget.Unset()
}

// GetRecallMaxTokens returns the RecallMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRecallMaxTokens() int32 {
	if o == nil || IsNil(o.RecallMaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.RecallMaxTokens.Get()
}

// GetRecallMaxTokensOk returns a tuple with the RecallMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRecallMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallMaxTokens.Get(), o.RecallMaxTokens.IsSet()
}

// HasRecallMaxTokens returns a boolean if a field has been set.
func (o *GroupResponse) HasRecallMaxTokens() bool {
	if o != nil && o.RecallMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetRecallMaxTokens gets a reference to the given NullableInt32 and assigns it to the RecallMaxTokens field.
func (o *GroupResponse) SetRecallMaxTokens(v int32) {
	o.RecallMaxTokens.Set(&v)
}
// SetRecallMaxTokensNil sets the value for RecallMaxTokens to be an explicit nil
func (o *GroupResponse) SetRecallMaxTokensNil() {
	o.RecallMaxTokens.Set(nil)
}

// UnsetRecallMaxTokens ensures that no value is present for RecallMaxTokens, not even an explicit nil
func (o *GroupResponse) UnsetRecallMaxTokens() {
	o.RecallMaxTokens.Unset()
}

// GetRecallTagGroups returns the RecallTagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRecallTagGroups() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.RecallTagGroups
}

// GetRecallTagGroupsOk returns a tuple with the RecallTagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRecallTagGroupsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.RecallTagGroups) {
		return nil, false
	}
	return o.RecallTagGroups, true
}

// HasRecallTagGroups returns a boolean if a field has been set.
func (o *GroupResponse) HasRecallTagGroups() bool {
	if o != nil && !IsNil(o.RecallTagGroups) {
		return true
	}

	return false
}

// SetRecallTagGroups gets a reference to the given []map[string]interface{} and assigns it to the RecallTagGroups field.
func (o *GroupResponse) SetRecallTagGroups(v []map[string]interface{}) {
	o.RecallTagGroups = v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel.Get()) {
		var ret string
		return ret
	}
	return *o.LlmModel.Get()
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetLlmModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmModel.Get(), o.LlmModel.IsSet()
}

// HasLlmModel returns a boolean if a field has been set.
func (o *GroupResponse) HasLlmModel() bool {
	if o != nil && o.LlmModel.IsSet() {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given NullableString and assigns it to the LlmModel field.
func (o *GroupResponse) SetLlmModel(v string) {
	o.LlmModel.Set(&v)
}
// SetLlmModelNil sets the value for LlmModel to be an explicit nil
func (o *GroupResponse) SetLlmModelNil() {
	o.LlmModel.Set(nil)
}

// UnsetLlmModel ensures that no value is present for LlmModel, not even an explicit nil
func (o *GroupResponse) UnsetLlmModel() {
	o.LlmModel.Unset()
}

// GetLlmProvider returns the LlmProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetLlmProvider() string {
	if o == nil || IsNil(o.LlmProvider.Get()) {
		var ret string
		return ret
	}
	return *o.LlmProvider.Get()
}

// GetLlmProviderOk returns a tuple with the LlmProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetLlmProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmProvider.Get(), o.LlmProvider.IsSet()
}

// HasLlmProvider returns a boolean if a field has been set.
func (o *GroupResponse) HasLlmProvider() bool {
	if o != nil && o.LlmProvider.IsSet() {
		return true
	}

	return false
}

// SetLlmProvider gets a reference to the given NullableString and assigns it to the LlmProvider field.
func (o *GroupResponse) SetLlmProvider(v string) {
	o.LlmProvider.Set(&v)
}
// SetLlmProviderNil sets the value for LlmProvider to be an explicit nil
func (o *GroupResponse) SetLlmProviderNil() {
	o.LlmProvider.Set(nil)
}

// UnsetLlmProvider ensures that no value is present for LlmProvider, not even an explicit nil
func (o *GroupResponse) UnsetLlmProvider() {
	o.LlmProvider.Unset()
}

// GetExcludeProviders returns the ExcludeProviders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetExcludeProviders() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeProviders
}

// GetExcludeProvidersOk returns a tuple with the ExcludeProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetExcludeProvidersOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeProviders) {
		return nil, false
	}
	return o.ExcludeProviders, true
}

// HasExcludeProviders returns a boolean if a field has been set.
func (o *GroupResponse) HasExcludeProviders() bool {
	if o != nil && !IsNil(o.ExcludeProviders) {
		return true
	}

	return false
}

// SetExcludeProviders gets a reference to the given []string and assigns it to the ExcludeProviders field.
func (o *GroupResponse) SetExcludeProviders(v []string) {
	o.ExcludeProviders = v
}

// GetRetainStrategy returns the RetainStrategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupResponse) GetRetainStrategy() string {
	if o == nil || IsNil(o.RetainStrategy.Get()) {
		var ret string
		return ret
	}
	return *o.RetainStrategy.Get()
}

// GetRetainStrategyOk returns a tuple with the RetainStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupResponse) GetRetainStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainStrategy.Get(), o.RetainStrategy.IsSet()
}

// HasRetainStrategy returns a boolean if a field has been set.
func (o *GroupResponse) HasRetainStrategy() bool {
	if o != nil && o.RetainStrategy.IsSet() {
		return true
	}

	return false
}

// SetRetainStrategy gets a reference to the given NullableString and assigns it to the RetainStrategy field.
func (o *GroupResponse) SetRetainStrategy(v string) {
	o.RetainStrategy.Set(&v)
}
// SetRetainStrategyNil sets the value for RetainStrategy to be an explicit nil
func (o *GroupResponse) SetRetainStrategyNil() {
	o.RetainStrategy.Set(nil)
}

// UnsetRetainStrategy ensures that no value is present for RetainStrategy, not even an explicit nil
func (o *GroupResponse) UnsetRetainStrategy() {
	o.RetainStrategy.Unset()
}

func (o GroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display_name"] = o.DisplayName
	if o.Recall.IsSet() {
		toSerialize["recall"] = o.Recall.Get()
	}
	if o.Retain.IsSet() {
		toSerialize["retain"] = o.Retain.Get()
	}
	if o.RetainRoles != nil {
		toSerialize["retain_roles"] = o.RetainRoles
	}
	if o.RetainTags != nil {
		toSerialize["retain_tags"] = o.RetainTags
	}
	if o.RetainEveryNTurns.IsSet() {
		toSerialize["retain_every_n_turns"] = o.RetainEveryNTurns.Get()
	}
	if o.RecallBudget.IsSet() {
		toSerialize["recall_budget"] = o.RecallBudget.Get()
	}
	if o.RecallMaxTokens.IsSet() {
		toSerialize["recall_max_tokens"] = o.RecallMaxTokens.Get()
	}
	if o.RecallTagGroups != nil {
		toSerialize["recall_tag_groups"] = o.RecallTagGroups
	}
	if o.LlmModel.IsSet() {
		toSerialize["llm_model"] = o.LlmModel.Get()
	}
	if o.LlmProvider.IsSet() {
		toSerialize["llm_provider"] = o.LlmProvider.Get()
	}
	if o.ExcludeProviders != nil {
		toSerialize["exclude_providers"] = o.ExcludeProviders
	}
	if o.RetainStrategy.IsSet() {
		toSerialize["retain_strategy"] = o.RetainStrategy.Get()
	}
	return toSerialize, nil
}

func (o *GroupResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupResponse := _GroupResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupResponse)

	if err != nil {
		return err
	}

	*o = GroupResponse(varGroupResponse)

	return err
}

type NullableGroupResponse struct {
	value *GroupResponse
	isSet bool
}

func (v NullableGroupResponse) Get() *GroupResponse {
	return v.value
}

func (v *NullableGroupResponse) Set(val *GroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupResponse(val *GroupResponse) *NullableGroupResponse {
	return &NullableGroupResponse{value: val, isSet: true}
}

func (v NullableGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


