/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResolvedPermissionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolvedPermissionsResponse{}

// ResolvedPermissionsResponse Full resolved permissions returned by GET /debug/resolve.  Mirrors hindclaw_ext.models.ResolvedPermissions but as an HTTP response model.
type ResolvedPermissionsResponse struct {
	UserId string `json:"user_id"`
	IsAnonymous bool `json:"is_anonymous"`
	Recall bool `json:"recall"`
	Retain bool `json:"retain"`
	RetainRoles []string `json:"retain_roles"`
	RetainTags []string `json:"retain_tags"`
	RetainEveryNTurns int32 `json:"retain_every_n_turns"`
	RetainStrategy NullableString `json:"retain_strategy"`
	RecallBudget string `json:"recall_budget"`
	RecallMaxTokens int32 `json:"recall_max_tokens"`
	RecallTagGroups []map[string]interface{} `json:"recall_tag_groups"`
	LlmModel NullableString `json:"llm_model"`
	LlmProvider NullableString `json:"llm_provider"`
	ExcludeProviders []string `json:"exclude_providers"`
}

type _ResolvedPermissionsResponse ResolvedPermissionsResponse

// NewResolvedPermissionsResponse instantiates a new ResolvedPermissionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolvedPermissionsResponse(userId string, isAnonymous bool, recall bool, retain bool, retainRoles []string, retainTags []string, retainEveryNTurns int32, retainStrategy NullableString, recallBudget string, recallMaxTokens int32, recallTagGroups []map[string]interface{}, llmModel NullableString, llmProvider NullableString, excludeProviders []string) *ResolvedPermissionsResponse {
	this := ResolvedPermissionsResponse{}
	this.UserId = userId
	this.IsAnonymous = isAnonymous
	this.Recall = recall
	this.Retain = retain
	this.RetainRoles = retainRoles
	this.RetainTags = retainTags
	this.RetainEveryNTurns = retainEveryNTurns
	this.RetainStrategy = retainStrategy
	this.RecallBudget = recallBudget
	this.RecallMaxTokens = recallMaxTokens
	this.RecallTagGroups = recallTagGroups
	this.LlmModel = llmModel
	this.LlmProvider = llmProvider
	this.ExcludeProviders = excludeProviders
	return &this
}

// NewResolvedPermissionsResponseWithDefaults instantiates a new ResolvedPermissionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolvedPermissionsResponseWithDefaults() *ResolvedPermissionsResponse {
	this := ResolvedPermissionsResponse{}
	return &this
}

// GetUserId returns the UserId field value
func (o *ResolvedPermissionsResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ResolvedPermissionsResponse) SetUserId(v string) {
	o.UserId = v
}

// GetIsAnonymous returns the IsAnonymous field value
func (o *ResolvedPermissionsResponse) GetIsAnonymous() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAnonymous
}

// GetIsAnonymousOk returns a tuple with the IsAnonymous field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetIsAnonymousOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAnonymous, true
}

// SetIsAnonymous sets field value
func (o *ResolvedPermissionsResponse) SetIsAnonymous(v bool) {
	o.IsAnonymous = v
}

// GetRecall returns the Recall field value
func (o *ResolvedPermissionsResponse) GetRecall() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Recall
}

// GetRecallOk returns a tuple with the Recall field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRecallOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recall, true
}

// SetRecall sets field value
func (o *ResolvedPermissionsResponse) SetRecall(v bool) {
	o.Recall = v
}

// GetRetain returns the Retain field value
func (o *ResolvedPermissionsResponse) GetRetain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Retain
}

// GetRetainOk returns a tuple with the Retain field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRetainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Retain, true
}

// SetRetain sets field value
func (o *ResolvedPermissionsResponse) SetRetain(v bool) {
	o.Retain = v
}

// GetRetainRoles returns the RetainRoles field value
func (o *ResolvedPermissionsResponse) GetRetainRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RetainRoles
}

// GetRetainRolesOk returns a tuple with the RetainRoles field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRetainRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainRoles, true
}

// SetRetainRoles sets field value
func (o *ResolvedPermissionsResponse) SetRetainRoles(v []string) {
	o.RetainRoles = v
}

// GetRetainTags returns the RetainTags field value
func (o *ResolvedPermissionsResponse) GetRetainTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RetainTags
}

// GetRetainTagsOk returns a tuple with the RetainTags field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRetainTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainTags, true
}

// SetRetainTags sets field value
func (o *ResolvedPermissionsResponse) SetRetainTags(v []string) {
	o.RetainTags = v
}

// GetRetainEveryNTurns returns the RetainEveryNTurns field value
func (o *ResolvedPermissionsResponse) GetRetainEveryNTurns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetainEveryNTurns
}

// GetRetainEveryNTurnsOk returns a tuple with the RetainEveryNTurns field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRetainEveryNTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetainEveryNTurns, true
}

// SetRetainEveryNTurns sets field value
func (o *ResolvedPermissionsResponse) SetRetainEveryNTurns(v int32) {
	o.RetainEveryNTurns = v
}

// GetRetainStrategy returns the RetainStrategy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ResolvedPermissionsResponse) GetRetainStrategy() string {
	if o == nil || o.RetainStrategy.Get() == nil {
		var ret string
		return ret
	}

	return *o.RetainStrategy.Get()
}

// GetRetainStrategyOk returns a tuple with the RetainStrategy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResolvedPermissionsResponse) GetRetainStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainStrategy.Get(), o.RetainStrategy.IsSet()
}

// SetRetainStrategy sets field value
func (o *ResolvedPermissionsResponse) SetRetainStrategy(v string) {
	o.RetainStrategy.Set(&v)
}

// GetRecallBudget returns the RecallBudget field value
func (o *ResolvedPermissionsResponse) GetRecallBudget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecallBudget
}

// GetRecallBudgetOk returns a tuple with the RecallBudget field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRecallBudgetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecallBudget, true
}

// SetRecallBudget sets field value
func (o *ResolvedPermissionsResponse) SetRecallBudget(v string) {
	o.RecallBudget = v
}

// GetRecallMaxTokens returns the RecallMaxTokens field value
func (o *ResolvedPermissionsResponse) GetRecallMaxTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RecallMaxTokens
}

// GetRecallMaxTokensOk returns a tuple with the RecallMaxTokens field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetRecallMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecallMaxTokens, true
}

// SetRecallMaxTokens sets field value
func (o *ResolvedPermissionsResponse) SetRecallMaxTokens(v int32) {
	o.RecallMaxTokens = v
}

// GetRecallTagGroups returns the RecallTagGroups field value
// If the value is explicit nil, the zero value for []map[string]interface{} will be returned
func (o *ResolvedPermissionsResponse) GetRecallTagGroups() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.RecallTagGroups
}

// GetRecallTagGroupsOk returns a tuple with the RecallTagGroups field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResolvedPermissionsResponse) GetRecallTagGroupsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.RecallTagGroups) {
		return nil, false
	}
	return o.RecallTagGroups, true
}

// SetRecallTagGroups sets field value
func (o *ResolvedPermissionsResponse) SetRecallTagGroups(v []map[string]interface{}) {
	o.RecallTagGroups = v
}

// GetLlmModel returns the LlmModel field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ResolvedPermissionsResponse) GetLlmModel() string {
	if o == nil || o.LlmModel.Get() == nil {
		var ret string
		return ret
	}

	return *o.LlmModel.Get()
}

// GetLlmModelOk returns a tuple with the LlmModel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResolvedPermissionsResponse) GetLlmModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmModel.Get(), o.LlmModel.IsSet()
}

// SetLlmModel sets field value
func (o *ResolvedPermissionsResponse) SetLlmModel(v string) {
	o.LlmModel.Set(&v)
}

// GetLlmProvider returns the LlmProvider field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ResolvedPermissionsResponse) GetLlmProvider() string {
	if o == nil || o.LlmProvider.Get() == nil {
		var ret string
		return ret
	}

	return *o.LlmProvider.Get()
}

// GetLlmProviderOk returns a tuple with the LlmProvider field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResolvedPermissionsResponse) GetLlmProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmProvider.Get(), o.LlmProvider.IsSet()
}

// SetLlmProvider sets field value
func (o *ResolvedPermissionsResponse) SetLlmProvider(v string) {
	o.LlmProvider.Set(&v)
}

// GetExcludeProviders returns the ExcludeProviders field value
func (o *ResolvedPermissionsResponse) GetExcludeProviders() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ExcludeProviders
}

// GetExcludeProvidersOk returns a tuple with the ExcludeProviders field value
// and a boolean to check if the value has been set.
func (o *ResolvedPermissionsResponse) GetExcludeProvidersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExcludeProviders, true
}

// SetExcludeProviders sets field value
func (o *ResolvedPermissionsResponse) SetExcludeProviders(v []string) {
	o.ExcludeProviders = v
}

func (o ResolvedPermissionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolvedPermissionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["is_anonymous"] = o.IsAnonymous
	toSerialize["recall"] = o.Recall
	toSerialize["retain"] = o.Retain
	toSerialize["retain_roles"] = o.RetainRoles
	toSerialize["retain_tags"] = o.RetainTags
	toSerialize["retain_every_n_turns"] = o.RetainEveryNTurns
	toSerialize["retain_strategy"] = o.RetainStrategy.Get()
	toSerialize["recall_budget"] = o.RecallBudget
	toSerialize["recall_max_tokens"] = o.RecallMaxTokens
	if o.RecallTagGroups != nil {
		toSerialize["recall_tag_groups"] = o.RecallTagGroups
	}
	toSerialize["llm_model"] = o.LlmModel.Get()
	toSerialize["llm_provider"] = o.LlmProvider.Get()
	toSerialize["exclude_providers"] = o.ExcludeProviders
	return toSerialize, nil
}

func (o *ResolvedPermissionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"is_anonymous",
		"recall",
		"retain",
		"retain_roles",
		"retain_tags",
		"retain_every_n_turns",
		"retain_strategy",
		"recall_budget",
		"recall_max_tokens",
		"recall_tag_groups",
		"llm_model",
		"llm_provider",
		"exclude_providers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolvedPermissionsResponse := _ResolvedPermissionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResolvedPermissionsResponse)

	if err != nil {
		return err
	}

	*o = ResolvedPermissionsResponse(varResolvedPermissionsResponse)

	return err
}

type NullableResolvedPermissionsResponse struct {
	value *ResolvedPermissionsResponse
	isSet bool
}

func (v NullableResolvedPermissionsResponse) Get() *ResolvedPermissionsResponse {
	return v.value
}

func (v *NullableResolvedPermissionsResponse) Set(val *ResolvedPermissionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResolvedPermissionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResolvedPermissionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolvedPermissionsResponse(val *ResolvedPermissionsResponse) *NullableResolvedPermissionsResponse {
	return &NullableResolvedPermissionsResponse{value: val, isSet: true}
}

func (v NullableResolvedPermissionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolvedPermissionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


