/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StrategyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategyRequest{}

// StrategyRequest struct for StrategyRequest
type StrategyRequest struct {
	Strategy string `json:"strategy"`
}

type _StrategyRequest StrategyRequest

// NewStrategyRequest instantiates a new StrategyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategyRequest(strategy string) *StrategyRequest {
	this := StrategyRequest{}
	this.Strategy = strategy
	return &this
}

// NewStrategyRequestWithDefaults instantiates a new StrategyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyRequestWithDefaults() *StrategyRequest {
	this := StrategyRequest{}
	return &this
}

// GetStrategy returns the Strategy field value
func (o *StrategyRequest) GetStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value
// and a boolean to check if the value has been set.
func (o *StrategyRequest) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Strategy, true
}

// SetStrategy sets field value
func (o *StrategyRequest) SetStrategy(v string) {
	o.Strategy = v
}

func (o StrategyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["strategy"] = o.Strategy
	return toSerialize, nil
}

func (o *StrategyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"strategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategyRequest := _StrategyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStrategyRequest)

	if err != nil {
		return err
	}

	*o = StrategyRequest(varStrategyRequest)

	return err
}

type NullableStrategyRequest struct {
	value *StrategyRequest
	isSet bool
}

func (v NullableStrategyRequest) Get() *StrategyRequest {
	return v.value
}

func (v *NullableStrategyRequest) Set(val *StrategyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategyRequest(val *StrategyRequest) *NullableStrategyRequest {
	return &NullableStrategyRequest{value: val, isSet: true}
}

func (v NullableStrategyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


