/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupMemberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupMemberResponse{}

// GroupMemberResponse Group membership entry.
type GroupMemberResponse struct {
	UserId string `json:"user_id"`
}

type _GroupMemberResponse GroupMemberResponse

// NewGroupMemberResponse instantiates a new GroupMemberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupMemberResponse(userId string) *GroupMemberResponse {
	this := GroupMemberResponse{}
	this.UserId = userId
	return &this
}

// NewGroupMemberResponseWithDefaults instantiates a new GroupMemberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupMemberResponseWithDefaults() *GroupMemberResponse {
	this := GroupMemberResponse{}
	return &this
}

// GetUserId returns the UserId field value
func (o *GroupMemberResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GroupMemberResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GroupMemberResponse) SetUserId(v string) {
	o.UserId = v
}

func (o GroupMemberResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupMemberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *GroupMemberResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupMemberResponse := _GroupMemberResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupMemberResponse)

	if err != nil {
		return err
	}

	*o = GroupMemberResponse(varGroupMemberResponse)

	return err
}

type NullableGroupMemberResponse struct {
	value *GroupMemberResponse
	isSet bool
}

func (v NullableGroupMemberResponse) Get() *GroupMemberResponse {
	return v.value
}

func (v *NullableGroupMemberResponse) Set(val *GroupMemberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupMemberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupMemberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupMemberResponse(val *GroupMemberResponse) *NullableGroupMemberResponse {
	return &NullableGroupMemberResponse{value: val, isSet: true}
}

func (v NullableGroupMemberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupMemberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


