/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StrategyScopeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategyScopeResponse{}

// StrategyScopeResponse Strategy scope entry returned by GET /banks/:bank/strategies.
type StrategyScopeResponse struct {
	BankId string `json:"bank_id"`
	ScopeType string `json:"scope_type"`
	ScopeValue string `json:"scope_value"`
	Strategy string `json:"strategy"`
}

type _StrategyScopeResponse StrategyScopeResponse

// NewStrategyScopeResponse instantiates a new StrategyScopeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategyScopeResponse(bankId string, scopeType string, scopeValue string, strategy string) *StrategyScopeResponse {
	this := StrategyScopeResponse{}
	this.BankId = bankId
	this.ScopeType = scopeType
	this.ScopeValue = scopeValue
	this.Strategy = strategy
	return &this
}

// NewStrategyScopeResponseWithDefaults instantiates a new StrategyScopeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyScopeResponseWithDefaults() *StrategyScopeResponse {
	this := StrategyScopeResponse{}
	return &this
}

// GetBankId returns the BankId field value
func (o *StrategyScopeResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *StrategyScopeResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *StrategyScopeResponse) SetBankId(v string) {
	o.BankId = v
}

// GetScopeType returns the ScopeType field value
func (o *StrategyScopeResponse) GetScopeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeType
}

// GetScopeTypeOk returns a tuple with the ScopeType field value
// and a boolean to check if the value has been set.
func (o *StrategyScopeResponse) GetScopeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeType, true
}

// SetScopeType sets field value
func (o *StrategyScopeResponse) SetScopeType(v string) {
	o.ScopeType = v
}

// GetScopeValue returns the ScopeValue field value
func (o *StrategyScopeResponse) GetScopeValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeValue
}

// GetScopeValueOk returns a tuple with the ScopeValue field value
// and a boolean to check if the value has been set.
func (o *StrategyScopeResponse) GetScopeValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeValue, true
}

// SetScopeValue sets field value
func (o *StrategyScopeResponse) SetScopeValue(v string) {
	o.ScopeValue = v
}

// GetStrategy returns the Strategy field value
func (o *StrategyScopeResponse) GetStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value
// and a boolean to check if the value has been set.
func (o *StrategyScopeResponse) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Strategy, true
}

// SetStrategy sets field value
func (o *StrategyScopeResponse) SetStrategy(v string) {
	o.Strategy = v
}

func (o StrategyScopeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategyScopeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["scope_type"] = o.ScopeType
	toSerialize["scope_value"] = o.ScopeValue
	toSerialize["strategy"] = o.Strategy
	return toSerialize, nil
}

func (o *StrategyScopeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"scope_type",
		"scope_value",
		"strategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategyScopeResponse := _StrategyScopeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStrategyScopeResponse)

	if err != nil {
		return err
	}

	*o = StrategyScopeResponse(varStrategyScopeResponse)

	return err
}

type NullableStrategyScopeResponse struct {
	value *StrategyScopeResponse
	isSet bool
}

func (v NullableStrategyScopeResponse) Get() *StrategyScopeResponse {
	return v.value
}

func (v *NullableStrategyScopeResponse) Set(val *StrategyScopeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategyScopeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategyScopeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategyScopeResponse(val *StrategyScopeResponse) *NullableStrategyScopeResponse {
	return &NullableStrategyScopeResponse{value: val, isSet: true}
}

func (v NullableStrategyScopeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategyScopeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


