/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiKeyCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyCreateResponse{}

// ApiKeyCreateResponse API key at creation time — full key shown once.
type ApiKeyCreateResponse struct {
	Id string `json:"id"`
	ApiKey string `json:"api_key"`
	Description NullableString `json:"description,omitempty"`
}

type _ApiKeyCreateResponse ApiKeyCreateResponse

// NewApiKeyCreateResponse instantiates a new ApiKeyCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyCreateResponse(id string, apiKey string) *ApiKeyCreateResponse {
	this := ApiKeyCreateResponse{}
	this.Id = id
	this.ApiKey = apiKey
	return &this
}

// NewApiKeyCreateResponseWithDefaults instantiates a new ApiKeyCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyCreateResponseWithDefaults() *ApiKeyCreateResponse {
	this := ApiKeyCreateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *ApiKeyCreateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiKeyCreateResponse) SetId(v string) {
	o.Id = v
}

// GetApiKey returns the ApiKey field value
func (o *ApiKeyCreateResponse) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreateResponse) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *ApiKeyCreateResponse) SetApiKey(v string) {
	o.ApiKey = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKeyCreateResponse) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyCreateResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiKeyCreateResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ApiKeyCreateResponse) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ApiKeyCreateResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ApiKeyCreateResponse) UnsetDescription() {
	o.Description.Unset()
}

func (o ApiKeyCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["api_key"] = o.ApiKey
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

func (o *ApiKeyCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiKeyCreateResponse := _ApiKeyCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiKeyCreateResponse)

	if err != nil {
		return err
	}

	*o = ApiKeyCreateResponse(varApiKeyCreateResponse)

	return err
}

type NullableApiKeyCreateResponse struct {
	value *ApiKeyCreateResponse
	isSet bool
}

func (v NullableApiKeyCreateResponse) Get() *ApiKeyCreateResponse {
	return v.value
}

func (v *NullableApiKeyCreateResponse) Set(val *ApiKeyCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyCreateResponse(val *ApiKeyCreateResponse) *NullableApiKeyCreateResponse {
	return &NullableApiKeyCreateResponse{value: val, isSet: true}
}

func (v NullableApiKeyCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


