/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpsertConfirmation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertConfirmation{}

// UpsertConfirmation Confirmation returned by PUT (upsert) endpoints.
type UpsertConfirmation struct {
	BankId string `json:"bank_id"`
	ScopeType string `json:"scope_type"`
	ScopeId string `json:"scope_id"`
}

type _UpsertConfirmation UpsertConfirmation

// NewUpsertConfirmation instantiates a new UpsertConfirmation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertConfirmation(bankId string, scopeType string, scopeId string) *UpsertConfirmation {
	this := UpsertConfirmation{}
	this.BankId = bankId
	this.ScopeType = scopeType
	this.ScopeId = scopeId
	return &this
}

// NewUpsertConfirmationWithDefaults instantiates a new UpsertConfirmation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertConfirmationWithDefaults() *UpsertConfirmation {
	this := UpsertConfirmation{}
	return &this
}

// GetBankId returns the BankId field value
func (o *UpsertConfirmation) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *UpsertConfirmation) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *UpsertConfirmation) SetBankId(v string) {
	o.BankId = v
}

// GetScopeType returns the ScopeType field value
func (o *UpsertConfirmation) GetScopeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeType
}

// GetScopeTypeOk returns a tuple with the ScopeType field value
// and a boolean to check if the value has been set.
func (o *UpsertConfirmation) GetScopeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeType, true
}

// SetScopeType sets field value
func (o *UpsertConfirmation) SetScopeType(v string) {
	o.ScopeType = v
}

// GetScopeId returns the ScopeId field value
func (o *UpsertConfirmation) GetScopeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value
// and a boolean to check if the value has been set.
func (o *UpsertConfirmation) GetScopeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeId, true
}

// SetScopeId sets field value
func (o *UpsertConfirmation) SetScopeId(v string) {
	o.ScopeId = v
}

func (o UpsertConfirmation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertConfirmation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["scope_type"] = o.ScopeType
	toSerialize["scope_id"] = o.ScopeId
	return toSerialize, nil
}

func (o *UpsertConfirmation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"scope_type",
		"scope_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertConfirmation := _UpsertConfirmation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpsertConfirmation)

	if err != nil {
		return err
	}

	*o = UpsertConfirmation(varUpsertConfirmation)

	return err
}

type NullableUpsertConfirmation struct {
	value *UpsertConfirmation
	isSet bool
}

func (v NullableUpsertConfirmation) Get() *UpsertConfirmation {
	return v.value
}

func (v *NullableUpsertConfirmation) Set(val *UpsertConfirmation) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertConfirmation) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertConfirmation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertConfirmation(val *UpsertConfirmation) *NullableUpsertConfirmation {
	return &NullableUpsertConfirmation{value: val, isSet: true}
}

func (v NullableUpsertConfirmation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertConfirmation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


