/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddMemberRequest{}

// AddMemberRequest struct for AddMemberRequest
type AddMemberRequest struct {
	UserId string `json:"user_id"`
}

type _AddMemberRequest AddMemberRequest

// NewAddMemberRequest instantiates a new AddMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddMemberRequest(userId string) *AddMemberRequest {
	this := AddMemberRequest{}
	this.UserId = userId
	return &this
}

// NewAddMemberRequestWithDefaults instantiates a new AddMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddMemberRequestWithDefaults() *AddMemberRequest {
	this := AddMemberRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *AddMemberRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddMemberRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddMemberRequest) SetUserId(v string) {
	o.UserId = v
}

func (o AddMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *AddMemberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddMemberRequest := _AddMemberRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddMemberRequest)

	if err != nil {
		return err
	}

	*o = AddMemberRequest(varAddMemberRequest)

	return err
}

type NullableAddMemberRequest struct {
	value *AddMemberRequest
	isSet bool
}

func (v NullableAddMemberRequest) Get() *AddMemberRequest {
	return v.value
}

func (v *NullableAddMemberRequest) Set(val *AddMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddMemberRequest(val *AddMemberRequest) *NullableAddMemberRequest {
	return &NullableAddMemberRequest{value: val, isSet: true}
}

func (v NullableAddMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


