/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupSummaryResponse{}

// GroupSummaryResponse Group summary returned by GET /groups (list view).
type GroupSummaryResponse struct {
	Id string `json:"id"`
	DisplayName string `json:"display_name"`
}

type _GroupSummaryResponse GroupSummaryResponse

// NewGroupSummaryResponse instantiates a new GroupSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupSummaryResponse(id string, displayName string) *GroupSummaryResponse {
	this := GroupSummaryResponse{}
	this.Id = id
	this.DisplayName = displayName
	return &this
}

// NewGroupSummaryResponseWithDefaults instantiates a new GroupSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupSummaryResponseWithDefaults() *GroupSummaryResponse {
	this := GroupSummaryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GroupSummaryResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupSummaryResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupSummaryResponse) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *GroupSummaryResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *GroupSummaryResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *GroupSummaryResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o GroupSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display_name"] = o.DisplayName
	return toSerialize, nil
}

func (o *GroupSummaryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupSummaryResponse := _GroupSummaryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupSummaryResponse)

	if err != nil {
		return err
	}

	*o = GroupSummaryResponse(varGroupSummaryResponse)

	return err
}

type NullableGroupSummaryResponse struct {
	value *GroupSummaryResponse
	isSet bool
}

func (v NullableGroupSummaryResponse) Get() *GroupSummaryResponse {
	return v.value
}

func (v *NullableGroupSummaryResponse) Set(val *GroupSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupSummaryResponse(val *GroupSummaryResponse) *NullableGroupSummaryResponse {
	return &NullableGroupSummaryResponse{value: val, isSet: true}
}

func (v NullableGroupSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


