/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddChannelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddChannelRequest{}

// AddChannelRequest struct for AddChannelRequest
type AddChannelRequest struct {
	Provider string `json:"provider"`
	SenderId string `json:"sender_id"`
}

type _AddChannelRequest AddChannelRequest

// NewAddChannelRequest instantiates a new AddChannelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddChannelRequest(provider string, senderId string) *AddChannelRequest {
	this := AddChannelRequest{}
	this.Provider = provider
	this.SenderId = senderId
	return &this
}

// NewAddChannelRequestWithDefaults instantiates a new AddChannelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddChannelRequestWithDefaults() *AddChannelRequest {
	this := AddChannelRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *AddChannelRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *AddChannelRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *AddChannelRequest) SetProvider(v string) {
	o.Provider = v
}

// GetSenderId returns the SenderId field value
func (o *AddChannelRequest) GetSenderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SenderId
}

// GetSenderIdOk returns a tuple with the SenderId field value
// and a boolean to check if the value has been set.
func (o *AddChannelRequest) GetSenderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SenderId, true
}

// SetSenderId sets field value
func (o *AddChannelRequest) SetSenderId(v string) {
	o.SenderId = v
}

func (o AddChannelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddChannelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["sender_id"] = o.SenderId
	return toSerialize, nil
}

func (o *AddChannelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"sender_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddChannelRequest := _AddChannelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddChannelRequest)

	if err != nil {
		return err
	}

	*o = AddChannelRequest(varAddChannelRequest)

	return err
}

type NullableAddChannelRequest struct {
	value *AddChannelRequest
	isSet bool
}

func (v NullableAddChannelRequest) Get() *AddChannelRequest {
	return v.value
}

func (v *NullableAddChannelRequest) Set(val *AddChannelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddChannelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddChannelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddChannelRequest(val *AddChannelRequest) *NullableAddChannelRequest {
	return &NullableAddChannelRequest{value: val, isSet: true}
}

func (v NullableAddChannelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddChannelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


