/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupMembershipConfirmation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupMembershipConfirmation{}

// GroupMembershipConfirmation Confirmation returned by POST /groups/:id/members.
type GroupMembershipConfirmation struct {
	GroupId string `json:"group_id"`
	UserId string `json:"user_id"`
}

type _GroupMembershipConfirmation GroupMembershipConfirmation

// NewGroupMembershipConfirmation instantiates a new GroupMembershipConfirmation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupMembershipConfirmation(groupId string, userId string) *GroupMembershipConfirmation {
	this := GroupMembershipConfirmation{}
	this.GroupId = groupId
	this.UserId = userId
	return &this
}

// NewGroupMembershipConfirmationWithDefaults instantiates a new GroupMembershipConfirmation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupMembershipConfirmationWithDefaults() *GroupMembershipConfirmation {
	this := GroupMembershipConfirmation{}
	return &this
}

// GetGroupId returns the GroupId field value
func (o *GroupMembershipConfirmation) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *GroupMembershipConfirmation) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *GroupMembershipConfirmation) SetGroupId(v string) {
	o.GroupId = v
}

// GetUserId returns the UserId field value
func (o *GroupMembershipConfirmation) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GroupMembershipConfirmation) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GroupMembershipConfirmation) SetUserId(v string) {
	o.UserId = v
}

func (o GroupMembershipConfirmation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupMembershipConfirmation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group_id"] = o.GroupId
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *GroupMembershipConfirmation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group_id",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupMembershipConfirmation := _GroupMembershipConfirmation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupMembershipConfirmation)

	if err != nil {
		return err
	}

	*o = GroupMembershipConfirmation(varGroupMembershipConfirmation)

	return err
}

type NullableGroupMembershipConfirmation struct {
	value *GroupMembershipConfirmation
	isSet bool
}

func (v NullableGroupMembershipConfirmation) Get() *GroupMembershipConfirmation {
	return v.value
}

func (v *NullableGroupMembershipConfirmation) Set(val *GroupMembershipConfirmation) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupMembershipConfirmation) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupMembershipConfirmation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupMembershipConfirmation(val *GroupMembershipConfirmation) *NullableGroupMembershipConfirmation {
	return &NullableGroupMembershipConfirmation{value: val, isSet: true}
}

func (v NullableGroupMembershipConfirmation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupMembershipConfirmation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


