# coding: utf-8

"""
    Hindclaw API

    Access control API for Hindsight memory server

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BankPermissionRequest(BaseModel):
    """
    BankPermissionRequest
    """ # noqa: E501
    recall: Optional[StrictBool] = None
    retain: Optional[StrictBool] = None
    retain_roles: Optional[List[StrictStr]] = None
    retain_tags: Optional[List[StrictStr]] = None
    retain_every_n_turns: Optional[StrictInt] = None
    recall_budget: Optional[StrictStr] = None
    recall_max_tokens: Optional[StrictInt] = None
    recall_tag_groups: Optional[List[Dict[str, Any]]] = None
    llm_model: Optional[StrictStr] = None
    llm_provider: Optional[StrictStr] = None
    exclude_providers: Optional[List[StrictStr]] = None
    retain_strategy: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["recall", "retain", "retain_roles", "retain_tags", "retain_every_n_turns", "recall_budget", "recall_max_tokens", "recall_tag_groups", "llm_model", "llm_provider", "exclude_providers", "retain_strategy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankPermissionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if recall (nullable) is None
        # and model_fields_set contains the field
        if self.recall is None and "recall" in self.model_fields_set:
            _dict['recall'] = None

        # set to None if retain (nullable) is None
        # and model_fields_set contains the field
        if self.retain is None and "retain" in self.model_fields_set:
            _dict['retain'] = None

        # set to None if retain_roles (nullable) is None
        # and model_fields_set contains the field
        if self.retain_roles is None and "retain_roles" in self.model_fields_set:
            _dict['retain_roles'] = None

        # set to None if retain_tags (nullable) is None
        # and model_fields_set contains the field
        if self.retain_tags is None and "retain_tags" in self.model_fields_set:
            _dict['retain_tags'] = None

        # set to None if retain_every_n_turns (nullable) is None
        # and model_fields_set contains the field
        if self.retain_every_n_turns is None and "retain_every_n_turns" in self.model_fields_set:
            _dict['retain_every_n_turns'] = None

        # set to None if recall_budget (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget is None and "recall_budget" in self.model_fields_set:
            _dict['recall_budget'] = None

        # set to None if recall_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.recall_max_tokens is None and "recall_max_tokens" in self.model_fields_set:
            _dict['recall_max_tokens'] = None

        # set to None if recall_tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.recall_tag_groups is None and "recall_tag_groups" in self.model_fields_set:
            _dict['recall_tag_groups'] = None

        # set to None if llm_model (nullable) is None
        # and model_fields_set contains the field
        if self.llm_model is None and "llm_model" in self.model_fields_set:
            _dict['llm_model'] = None

        # set to None if llm_provider (nullable) is None
        # and model_fields_set contains the field
        if self.llm_provider is None and "llm_provider" in self.model_fields_set:
            _dict['llm_provider'] = None

        # set to None if exclude_providers (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_providers is None and "exclude_providers" in self.model_fields_set:
            _dict['exclude_providers'] = None

        # set to None if retain_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.retain_strategy is None and "retain_strategy" in self.model_fields_set:
            _dict['retain_strategy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankPermissionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recall": obj.get("recall"),
            "retain": obj.get("retain"),
            "retain_roles": obj.get("retain_roles"),
            "retain_tags": obj.get("retain_tags"),
            "retain_every_n_turns": obj.get("retain_every_n_turns"),
            "recall_budget": obj.get("recall_budget"),
            "recall_max_tokens": obj.get("recall_max_tokens"),
            "recall_tag_groups": obj.get("recall_tag_groups"),
            "llm_model": obj.get("llm_model"),
            "llm_provider": obj.get("llm_provider"),
            "exclude_providers": obj.get("exclude_providers"),
            "retain_strategy": obj.get("retain_strategy")
        })
        return _obj


