# coding: utf-8

"""
    Hindclaw API

    Access control API for Hindsight memory server

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ResolvedPermissionsResponse(BaseModel):
    """
    Full resolved permissions returned by GET /debug/resolve.  Mirrors hindclaw_ext.models.ResolvedPermissions but as an HTTP response model.
    """ # noqa: E501
    user_id: StrictStr
    is_anonymous: StrictBool
    recall: StrictBool
    retain: StrictBool
    retain_roles: List[StrictStr]
    retain_tags: List[StrictStr]
    retain_every_n_turns: StrictInt
    retain_strategy: Optional[StrictStr]
    recall_budget: StrictStr
    recall_max_tokens: StrictInt
    recall_tag_groups: Optional[List[Dict[str, Any]]]
    llm_model: Optional[StrictStr]
    llm_provider: Optional[StrictStr]
    exclude_providers: List[StrictStr]
    __properties: ClassVar[List[str]] = ["user_id", "is_anonymous", "recall", "retain", "retain_roles", "retain_tags", "retain_every_n_turns", "retain_strategy", "recall_budget", "recall_max_tokens", "recall_tag_groups", "llm_model", "llm_provider", "exclude_providers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResolvedPermissionsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if retain_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.retain_strategy is None and "retain_strategy" in self.model_fields_set:
            _dict['retain_strategy'] = None

        # set to None if recall_tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.recall_tag_groups is None and "recall_tag_groups" in self.model_fields_set:
            _dict['recall_tag_groups'] = None

        # set to None if llm_model (nullable) is None
        # and model_fields_set contains the field
        if self.llm_model is None and "llm_model" in self.model_fields_set:
            _dict['llm_model'] = None

        # set to None if llm_provider (nullable) is None
        # and model_fields_set contains the field
        if self.llm_provider is None and "llm_provider" in self.model_fields_set:
            _dict['llm_provider'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResolvedPermissionsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "is_anonymous": obj.get("is_anonymous"),
            "recall": obj.get("recall"),
            "retain": obj.get("retain"),
            "retain_roles": obj.get("retain_roles"),
            "retain_tags": obj.get("retain_tags"),
            "retain_every_n_turns": obj.get("retain_every_n_turns"),
            "retain_strategy": obj.get("retain_strategy"),
            "recall_budget": obj.get("recall_budget"),
            "recall_max_tokens": obj.get("recall_max_tokens"),
            "recall_tag_groups": obj.get("recall_tag_groups"),
            "llm_model": obj.get("llm_model"),
            "llm_provider": obj.get("llm_provider"),
            "exclude_providers": obj.get("exclude_providers")
        })
        return _obj


